baseURL = 'https://da1sy-petals.vercel.app'
languageCode = 'zh-CN'
title = 'Da1sypetals'
theme = 'rusty-typewriter'

enableRobotsTXT = true

# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags', 'series']
countTaxonomy = 2147483647

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Da1sypetals'

[[menus.main]]
name = '知识'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = '文化'
pageRef = '/art'
weight = 2

[[menus.main]]
name = 'en-Posts'
pageRef = '/english-post'
weight = 3

[[menus.main]]
name = '文档'
pageRef = '/documents'
weight = 4

[[menus.main]]
name = '歌单'
url = 'https://daisy-songs.vercel.app'
weight = 8

[[menus.main]]
name = '关于我'
pageRef = '/about.md'
weight = 9


# build search index ================
[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['$', '$']]


[params]
math = true
